server:
  port: 8082

spring:
  application:
    name: data-ingestion-service
  datasource:
    url: jdbc:postgresql://postgres-features:5432/edupath_features
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: password
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    template:
      exchange: edupath.exchange
      default-receive-queue: ingestion.queue
      routing-key: ingestion.routing.key

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: data-ingestion-service
    prefer-ip-address: true

services:
  auth-service: http://auth-service:8081
  module-service: http://module-service:8083
  note-service: http://note-service:8084
  activities-service: http://activities-service:5000


